### PR TITLE
Add an alternative method for cmake 3.15+ with fewer side-effects

### LINKED ISSUE #130: hunter_venv changes CMAKE_FIND_FRAMEWORK unnecessarily
* I've read [Brief overview section](https://hunter.readthedocs.io/en/latest/overview.html) and do understand basic concepts. **[Yes]**
* I've read [F.A.Q. section](https://hunter.readthedocs.io/en/latest/faq.html) and there is no solution to my problem there. **[Yes]**
* I've read [Code of Conduct](https://github.com/cpp-pm/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. **[Yes]**
* I've read [Reporting bugs section](https://hunter.readthedocs.io/en/latest/contributing.html#reporting-bugs) carefully. **[Yes]**
* I've checked that all the `hunter_add_package`/`find_package` API used by me in the example is the same as in [documentation](https://hunter.readthedocs.io/en/latest/packages.html). **[Yes]**
* I'm using [latest](https://github.com/cpp-pm/hunter/releases) Hunter `URL`/`SHA1`. **[Yes]**

```cmake
# CMakeLists.txt

cmake_minimum_required(VERSION 3.15)

include("cmake/HunterGate.cmake")
HunterGate(
    URL "..."
    SHA1 "..."
)

project(foo)

hunter_add_package(hunter_venv)
find_package(hunter_venv CONFIG REQUIRED)

# Fails as CMAKE_FIND_FRAMEWORK set to NEVER
find_library(ACCEL Accelerate)
```

* I'm building on [OSX].
* [I'm using official CMake release]
* CMake version: <3.16.2>

---

Since cmake 3.15 a new option has been available `Python_FIND_VIRTUALENV`, which avoids the need to change the macOS global CMake setting `CMAKE_FIND_FRAMEWORK` and the Windows `Python_FIND_REGISTRY` (which is at least Python specific so probably OK).

I will need a hunter-packages for `hunter_venv` to make an update to it something like the following:

```cmake
if (version is >= 3.15)
  set(Python_FIND_VIRTUALENV ONLY)
else()
  set(CMAKE_FIND_FRAMEWORK NEVER)
  set(Python_FIND_REGISTRY NEVER)
endif()
```

### PR DESCRIPTION
**Pull request by hjmallon**
The change stops hunter_venv changing `CMAKE_FIND_FRAMEWORK` and `Python_FIND_REGISTRY` to `NEVER`, as a new way to choose virtualenv python has been introduced `Python_FIND_VIRTUALENV = ONLY`.

`CMAKE_FIND_FRAMEWORK=NEVER` stops useful things on macOS from working, such as:

```cmake
# Find the Accelerate Framework on macOS
find_library(ACCELERATE_LIBRARY Accelerate)
```

Test results building my test branch:
* https://travis-ci.org/hjmallon/hunter/builds/637880821
* https://ci.appveyor.com/project/hjmallon/hunter/builds/30154607

Fixes https://github.com/cpp-pm/hunter/issues/130

### CODE REVIEW

**Review by bkotzz — APPROVED** [review]
As far as testing goes, since we only install 3.15 in C.I. (https://github.com/cpp-pm/polly/blob/master/bin/install-ci-dependencies.py#L196) I guess only your new code path is being tested here. Which is fine - something to keep in mind if someone wants to change the old path. 

Also we may as well remove the python2 logic at some point now that it is deprecated...

**Comment by hjmallon** [comment]
Yep, good to remember that the 3.14 path isn't tested any more. We have the option to bump the cmake minimum version if we wanted to avoid that. I figured we coukd get away without chnaging that for now.

**Comment by hjmallon** [comment]
I just did a git pull and got some new tags (but more than I expected). Maybe some accidental extras? I expected `v1.0.2` only.

```sh
...
 * [new tag]         V1.0.2     -> V1.0.2
 * [new tag]         v1.0.2     -> v1.0.2
 * [new tag]         v1.0.2     -> v1.0.2
```

**Comment by bkotzz** [comment]
Hmm, seems there’s an extra tag, I’ll clean up. Feel free to ignore V1.0.2

**Pull request merged**
